### ISSUE TITLE
Turn your adblocker off for the following sites

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Blocker-database#14]
Hello friends, it's hard to get support these days and I want to start a thread where you can add your favorite pages which you want to support, aka toggling the adblockers off. 

We can use this thread to discuss which sites are 'okay' to support, which means that the pages not delivering dangerous ads or don't disturbing you while you read the articles.

1. chefkochblog.wordpress.com (silly me ... forgive me)
2. ghacks.net
3. askwoody.com
4. askvg.com
5. techcrunch.com
6. lifewire.com
7. paul4innovating.com
8. nbry.wordpress.com
9. blog.cryptographyengineering.com
10. zerobin.net
11. gog.com
12. pouet.net
13. scene.org
14. wj32.org
15. myce.com
16. msdn.rg-adguard.net 
17. appveyor.com / ci.appveyor.com
18. catalog.update.microsoft.com
19. news.ycombinator.com
20. chromium.woolyss.com
21. forums.sandboxie.com
22. dedoimedo.com
23. hartware.de
24. tweakpc.de
25. android.googlesource.com
26. desktop.firmware.mobi
27. chainfire.eu
28. repo.xposed.info
29. arstechnica.com
30. fudzilla.com
31. overclockers.ru
32. Mozilla.com
33. opensuse.org
34. ubuntu.com
35. distrowatch.com
36. wikipedia.org
37. w3schools.com
38. osnews.com
39. techsupportalert.com
40. fsf.org
41. opensource.org
42. ocsmag.com
43. eff.org
44. cfoi.org.uk
45. projectfreedom.cng1.com
46. statewatch.org
47. internetdefenseleague.org
48. cloudflare.com
49. eurodns.com
50. isen.com
51. couragefound.org
52. freehaven.net
53. aclu.org
54. leaksource.wordpress.com
55. snowdenarchive.cjfe.org
56. fveydocs.org
57. archive.is
58. cryptome.org
59. nordvpn.com
60. natsios-young.org

These are some quick pages which came to my mind and which might deserve some support, I totally get the point that it is not only abourt annoying ads more to reduce the overall bandwith or to stay away from trackers, the thing is that most known trackers are already included and there getting anyway blocked in case you use the strongest settings (which we are using). Most of these pages placing there ads well, mostly on the very left/right to not distrub you. 

Before I change something I want to hear your opinions, you of course can submit any page you want.

**Comment by X8716e** [comment]
gnu.org
fsf.org
eff.org
debian.org
altgov2.org
thememoryhole2.org

**Comment by X8716e** [comment]
I question many sites on the list, though. Nordvpn, techcrunch, yahoo news(!?), cloudfare, dedoimedo, distrowatch (half the site is ads is why), even ubuntu (distro is just one giant attack vector) & opensuse (ever wondered how/why they packed Silverlight in with the distro fairly long ago?)...

**Comment by CHEF-KOCH** [comment]
Some sites including my own simple need ads to survive. The difference is how well the ads are placed, if they're dangerous or not and if that page collects data or not. 'Overblocking' everything is in my opinion not good for all of us and ends up with only stronger methods to bypass it.

You list will be added in the next release. Btw there is no YahooNews ....
