### ISSUE TITLE
uMatrix + uBlock combo settings are wronger than wrong

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Blocker-database#19]
**Problem**
The current settings are not good enough because the websites are marked as green which is similar like "no blocking". I already changed it, don't worry but I need a bit more time to push it.

**Did I screw'ed it up?**
Depending how you see it, my excuse is that back in the time uBo & uMatrix leaked several things (_but that's all fixed now_).

However, people can judge me because I did not mention it fast enough because I had no time to push the already changed settings, so at this time I need to apologize!

![uM](https://user-images.githubusercontent.com/727123/72208450-0667c900-34a3-11ea-83f5-b5725f718541.png)

**Comment by txtsd** [comment]
Bad bot!

**Comment by CHEF-KOCH** [comment]
Done.
