### ISSUE TITLE
CanvasBlocker-settings_2019-11-11_16-05-25.json

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/Blocker-database#20]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

I can't install that archive in fennec in Canvas.
I havent permissions. How i install this .json in canvasblocker in fennec?.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock/.. version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by CHEF-KOCH** [comment]
Fennec is not supported, as said many times now across other repositories, Android works different from other OS. 

This is a security limitation and by design.
