### ISSUE TITLE
uBlock sync issue

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Blocker-database#5]
On a huge filter-list (like we have) uB refuses to sync (due it's limitation).

**Steps to reproduce**:
* Install Chrome/Firefox (stable/Nightly/dev/can.)
* Install latest uB 
* Import the filter lists manually from this repo
* Login in Google/Mozilla sync accounts [or with your own sync provider (only Mozilla)]
* Try to sync it to the cloud.
* 'My filters' never sync due a bug ... Same is in uMatrix (copy & pasta source -> same bug)

![wdw](https://user-images.githubusercontent.com/727123/29976375-1b009d94-8f3a-11e7-905e-f8af27b2ba64.gif)

**Comment by The-Commissioner** [comment]
@CHEF-KOCH How are you syncing the files? What mechanism are you using?

**Comment by CHEF-KOCH** [comment]
I spoke with Mozilla and Google, they have no sync limit, only limitation is that you can't upload/download unlimited, there is an API limit ~1000 but normally you never reach that per day.

**Comment by The-Commissioner** [comment]
Ok thanx, I was trying to modify your static filter list in alphabetical sort-order but I'm new to github repository thingy, so don't know how. :-P

**Comment by CHEF-KOCH** [comment]
Well I appropriate your effort to help to push this little project here. Every pull request is welcome. About the alphabetical order, I dunno if that is necessary, cause it not 'increases' loading times and as soon I add stuff I need to re-do it, so I suggest to not waste your time on this. 

Instead maybe you find problematically entrance or something which can be 'improved' - that's more what I'm looking for. Of course everything is up to you, I not request a pull request as long there are valid reasons.

**Comment by CHEF-KOCH** [comment]
It appears that every sync is 'blocked' as soon you reach a specific file size that not only affects uBlock - also uMatrix. This implementation is BS because why you integrate some limitation when Google doesn't have one (except 1000 sync request per each API key?).
